include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - test/generated/**
    - scratch.dart
    - scratch/**
    - build/**
    - android/**
    - ios/**
    - macos/**
    - web/**
    - windows/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - signals_lint

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_positional_boolean_parameters: false
    directives_ordering: true
    leading_newlines_in_multiline_strings: false
    lines_longer_than_80_chars: false
    prefer_final_locals: true
    public_member_api_docs: false
    require_trailing_commas: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    unawaited_futures: true
    use_setters_to_change_properties: false
