targets:
  $default:
    builders:
      # Configure the Freezed builder
      freezed:
        generate_for:
          include:
            - lib/**.dart

      # Configure the JSON Serializable builder
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
        generate_for:
          include:
            - lib/**.dart

      # Configure the Riverpod Generator builder
      riverpod_generator:
        generate_for:
          include:
            - lib/**.dart

builders:
  # Add any custom builder configurations here
